version: 0.2
env:
  variables:
    NODE_ENV: production
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd apps/api && npm install
      - cd ../web && npm install
  build:
    commands:
      - cd apps/api && npm run build
      - cd ../web && npm run build
  post_build:
    commands:
      - aws s3 sync apps/web/dist/ s3://zippy-link --delete
      - zip -r backend.zip apps/api/dist/*
artifacts:
  files:
    - backend.zip
