version: 0.2
env:
  variables:
    NODE_ENV: production
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Clean npm cache and verify Node.js/npm versions
      - npm cache clean --force
      - node -v
      - npm -v
      # Check if the directory exists
      - cd apps/api
      - ls -la
      - npm install
      - cd ../web
      - npm install
  build:
    commands:
      - cd ../api 
      - npm run build
      - cd ../web 
      - npm run build
  post_build:
    commands:
      - cd ../../ 
      - aws s3 sync apps/web/dist/ s3://artifacts-zippy-link --delete
      - zip -r backend.zip apps/api/dist/*
artifacts:
  files:
    - backend.zip
